name: "Buld Extension"
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install dependencies
        run: npm install
      - name: Update version in manifest.json
        id: update_version
        run: |
          # Read the current version from manifest.json
          CURRENT_VERSION=$(jq -r '.version' manifest.json)
          
          # Extract the version prefix (1.1 in 1.1.152)
          VERSION_PREFIX=$(echo $CURRENT_VERSION | cut -d '.' -f 1-2)
          
          # Use GITHUB_RUN_NUMBER as the build number
          BUILD_NUMBER=${{ github.run_number }}
          
          # Create the new version
          NEW_VERSION="$VERSION_PREFIX.$BUILD_NUMBER"
          
          echo "Current version: $CURRENT_VERSION"
          echo "New version: $NEW_VERSION"
          
          # Update manifest.json with the new version
          jq --arg new_version "$NEW_VERSION" '.version = $new_version' manifest.json > manifest.json.tmp && mv manifest.json.tmp manifest.json

          # Set the new version as output
          echo "::set-output name=new_version::$NEW_VERSION"
      - name: Build
        run: npm run build
      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build

